### ISSUE TITLE
issues with java while attempting TagText

### ISSUE THREAD

**Issue by Orest02** [brown-uk/nlp_uk#11]
Was trying `TagText.groovy` and got:

`Caught: groovy.lang.GroovyRuntimeException: Could not find matching constructor for: java.io.File(Boolean)
groovy.lang.GroovyRuntimeException: Could not find matching constructor for: java.io.File(Boolean)
	at org.nlp_uk.tools.TextUtils.processByParagraph(Script1.groovy:21)
	at org.nlp_uk.tools.TextUtils$processByParagraph.call(Unknown Source)
	at org.nlp_uk.tools.TagText.process(TagText.groovy:398)
	at org.nlp_uk.tools.TagText$process$1.call(Unknown Source)
	at org.nlp_uk.tools.TagText.main(TagText.groovy:487)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)`

File I was trying to analyse -- [example.txt](https://github.com/brown-uk/nlp_uk/files/5214989/example.txt)

I'm on Ubuntu 18.04.5 LTS with java version "13.0.2" 2020-01-14

**Comment by arysin** [comment]
What arguments did you use and what version of groovy ?

**Comment by Orest02** [comment]
Groovy Version: 3.0.4 JVM: 13.0.2 Vendor: Oracle Corporation OS: Linux
The command I used was `groovy TagText.groovy -i example.txt output.txt`

**Comment by Orest02** [comment]
ok sorry i forgot the `-o` (facepalm)

**Comment by arysin** [comment]
Ahh, thanks, I've pushed a fix to fail more gracefully on (invalid) positional parameters
